### PR TITLE
Adding text and fixing permission yaml key

### PR DESCRIPTION
**Pull request by nerdstein**
Fixed permission key, had extraneous quotes

Added encryption service test

### CODE REVIEW

**Comment by nerdstein** [comment]
Please note - this test hangs on my local system.

There has been a lot of D8 work on the AJAX commands. I am thinking this may be an issue in core. The test runs clean if you comment out the AJAX request.

@mjl3475 - can you take a look at this?

**Comment by mjl3475** [comment]
Code looks good. Was unable to run the test on my machine for some reason. Trying to figure out why.

**Comment by nerdstein** [comment]
@mjl3475  - ready for a peer review. Requires pulling down Key again

**Comment by nerdstein** [comment]
Changes were made to both modules

**Comment by nerdstein** [comment]
Merging

**Pull request merged**
